--[[
    AutoClickerConfig.luau
    ─────────────────────────────────────────────────────────────────────────────
    Defines click rates (clicks per second) for each autoclicker level.
    Easier to balance than searching through AutoClickManager code.
--]]

return {
    [1] = 2,
    [2] = 4,
    [3] = 6,
    [4] = 8,
    [5] = 10,
    [6] = 12,
    [7] = 14,
    [8] = 16,
    [9] = 18,
    [10] = 20,
    [11] = 25,
    [12] = 30,
    [13] = 35,
    [14] = 40,
    [15] = 50,
    [16] = 0 
}
